/* Dictionnaire FR → EN complet du site (utilisé par site-extras.js). */
window.SJA_DICT_EN = {
"Image de fond":"Background image","Passer l'intro":"Skip intro",
"Vente France et UE":"Sales France & EU","Rachat cash":"Cash buyback","Export hors UE":"Export outside EU","Super Promos":"Super Deals",
"Catalogue":"Catalogue","Recherche":"Search","Marques":"Brands","Pourquoi nous":"Why us","Process":"Process","Témoignages":"Testimonials","Nos vidéos":"Our videos","Votre projet":"Your project","Contact":"Contact","Vidéos":"Videos","Infos":"Info","Nos véhicules":"Our vehicles",
"Vente automobile en France et à l'international":"Car sales in France and worldwide",
"La vente de véhicule sans frontières":"Vehicle sales without borders",
"Votre expert de la vente et de l'importation depuis plus de 20 ans. Des véhicules neufs et d'occasion rigoureusement sélectionnés, livrés jusqu'à votre porte.":"Your sales and import expert for over 20 years. Rigorously selected new and used vehicles, delivered to your door.",
"Voir nos véhicules":"See our vehicles","Nous contacter":"Contact us",
"véhicules disponibles":"vehicles available","marques partenaires":"partner brands","ans d'expertise":"years of expertise","défiler":"scroll",
"Nos véhicules disponibles":"Our available vehicles",
"Filtrez par marque, état et budget. Chaque véhicule est vérifié et prêt à rouler, pour la France comme pour l'export.":"Filter by brand, condition and budget. Every vehicle is inspected and ready to drive, for France as well as export.",
"Étape 1 · Sélectionnez votre marque":"Step 1 · Select your brand","Choisissez votre marque":"Choose your brand","Étape 2 · Affinez vos critères":"Step 2 · Refine your search",
"Marque":"Brand","Toutes · cliquez sur un logo":"All · click a logo","Tous":"All","Neuf":"New","Occasion":"Used",
"Modèle":"Model","Tous les modèles":"All models","Année":"Year","Toutes les années":"All years","Équipements":"Equipment","Filtrer par équipement":"Filter by equipment","Effacer":"Clear",
"Énergie":"Fuel","Toutes énergies":"All fuels","Boîte":"Gearbox","Toutes boîtes":"All gearboxes","Budget max":"Max budget","Tri":"Sort",
"Prix croissant":"Price: low to high","Prix décroissant":"Price: high to low","Plus récents":"Newest","Réinitialiser":"Reset",
"Nos deux activités":"Our two lines of business","Acheter ou vendre : choisissez votre voie":"Buying or selling: choose your path",
"SJA Passion 73, c'est deux métiers complémentaires. Dites-nous où vous en êtes.":"SJA Passion 73 covers two complementary trades. Tell us where you stand.",
"Vous cherchez un véhicule":"You are looking for a vehicle","Achat & Export":"Purchase & Export",
"Véhicules neufs et d'occasion rigoureusement sélectionnés, livrés en France et à l'international. Vente hors taxes possible à l'export.":"Rigorously selected new and used vehicles, delivered in France and worldwide. Tax-free sales available for export.",
"Vous vendez votre voiture":"You are selling your car",
"On inspecte votre véhicule et on vous remet une offre ferme et chiffrée sur place. Paiement rapide, démarches gérées par nos soins.":"We inspect your vehicle and hand you a firm, quantified offer on the spot. Fast payment, paperwork handled by us.",
"Estimer mon véhicule":"Get my car valued",
"Pourquoi nous choisir":"Why choose us","20 ans d'expertise à votre service":"20 years of expertise at your service",
"De la sélection du véhicule à la livraison à votre porte, nous maîtrisons toute la chaîne.":"From vehicle selection to delivery at your door, we master the entire chain.",
"Expertise 20 ans":"20 years of expertise",
"Un réseau de fournisseurs européens établi et des prix négociés au plus juste depuis deux décennies.":"An established network of European suppliers and sharply negotiated prices for two decades.",
"Accompagnement complet":"Full support",
"Vente, transit international, dédouanement et livraison : un interlocuteur unique du début à la fin.":"Sale, international transit, customs clearance and delivery: a single point of contact from start to finish.",
"Véhicules certifiés":"Certified vehicles",
"Chaque véhicule est inspecté, son historique vérifié et son dossier complet remis avant l'expédition.":"Every vehicle is inspected, its history checked and its complete file handed over before shipping.",
"Prix compétitifs":"Competitive prices",
"Une tarification transparente, sans frais cachés, pensée pour l'export à travers le Maghreb et l'Europe.":"Transparent pricing, no hidden fees, designed for export across the Maghreb and Europe.",
"Comment ça marche":"How it works","Votre véhicule en 4 étapes":"Your vehicle in 4 steps",
"Un parcours simple et transparent, suivi pas à pas par notre équipe.":"A simple, transparent journey, followed step by step by our team.",
"Vous choisissez":"You choose",
"Sélectionnez votre véhicule dans le catalogue ou confiez-nous votre recherche.":"Select your vehicle from the catalogue or entrust us with your search.",
"Vente & logistique":"Sale & logistics","Nous gérons la vente —":"We handle the sale —","hors taxes (HT) possible":"tax-free (excl. VAT) available","— le contrôle et l'organisation du transport.":"— inspection and transport organisation.",
"Transit, douane & formalités":"Transit, customs & formalities","Acheminement, dédouanement,":"Shipping, customs clearance,","formalités administratives et immatriculation provisoire":"administrative formalities and temporary registration",": nous nous occupons de tout.":": we take care of everything.",
"Livraison":"Delivery","Votre véhicule est livré à votre porte, prêt à rouler —":"Your vehicle is delivered to your door, ready to drive —","sous conditions":"subject to conditions",
"Vente hors taxes (HT) possible.":"Tax-free sales (excl. VAT) available.",
"Pour l'export hors UE, nous pouvons vous vendre votre véhicule hors taxes et vous faire bénéficier de l'exonération de TVA, sous conditions d'éligibilité.":"For export outside the EU, we can sell your vehicle tax-free and let you benefit from VAT exemption, subject to eligibility conditions.",
"Ils nous ont fait confiance":"They trusted us",
"Des centaines de clients livrés à travers le Maghreb et l'Europe.":"Hundreds of customers delivered across the Maghreb and Europe.",
"Contact & localisation":"Contact & location","Parlons de votre projet":"Let's talk about your project",
"Une question, un véhicule en tête ? Notre équipe vous répond rapidement.":"A question, a vehicle in mind? Our team replies quickly.",
"Merci ! Votre demande a bien été envoyée, nous vous recontactons très vite.":"Thank you! Your request has been sent — we will get back to you very soon.",
"Nom complet":"Full name","Veuillez indiquer votre nom.":"Please enter your name.","Email":"Email","Adresse email invalide.":"Invalid email address.",
"Téléphone":"Phone","Veuillez indiquer un téléphone.":"Please enter a phone number.","Pays de livraison":"Delivery country",
"Algérie":"Algeria","Tunisie":"Tunisia","Maroc":"Morocco","Libye":"Libya","Mauritanie":"Mauritania","France":"France","Belgique":"Belgium","Espagne":"Spain","Italie":"Italy","Allemagne":"Germany","Suisse":"Switzerland","Autre":"Other",
"Marque / modèle souhaité":"Desired make / model","Votre message":"Your message","Veuillez écrire votre message.":"Please write your message.","Envoyer ma demande":"Send my request",
"Adresse":"Address","3 agences · Savoie · Rhône · Paris":"3 branches · Savoie · Rhône · Paris","Horaires":"Opening hours","Lundi – Vendredi":"Monday – Friday","Samedi":"Saturday","Dimanche":"Sunday","Sur RDV":"By appointment",
"Nos agences":"Our branches","Trois points de vente · deux en Auvergne‑Rhône‑Alpes, un à Paris":"Three sales locations · two in Auvergne-Rhône-Alpes, one in Paris",
"Siège":"Head office","73260 · Savoie — Tarentaise":"73260 · Savoie — Tarentaise","Itinéraire":"Directions","69000 · Rhône":"69000 · Rhône","75012 · Paris 12":"75012 · Paris 12",
"Votre expert de l'importation de véhicules neufs et d'occasion à travers le Maghreb et l'Europe depuis plus de 20 ans.":"Your expert in importing new and used vehicles across the Maghreb and Europe for over 20 years.",
"Navigation":"Navigation","Véhicules":"Vehicles","Société":"Company","Super Promo Intra UE":"Super Deals Intra EU","Super Promo Extra UE":"Super Deals Extra EU",
"Légal":"Legal","Mentions légales":"Legal notice","CGV":"Terms of sale","Confidentialité":"Privacy","Cookies":"Cookies",
"© 2026 SJA Passion 73. Tous droits réservés.":"© 2026 SJA Passion 73. All rights reserved.",
"Contact WhatsApp":"WhatsApp contact","Demande de renseignements":"Information request",
"Gestion des photos par modèle":"Photo management per model",
"Déposez 3 photos par modèle (face / profil / intérieur). Elles s'appliquent à":"Drop 3 photos per model (front / side / interior). They apply to","toutes":"all","les annonces de ce modèle.":"listings of this model.",
"Tout réinitialiser":"Reset everything",
"Estimation":"Valuation","Votre voiture vaut du cash.":"Your car is worth cash.","Tout de suite.":"Right now.",
"Vous vendez, on évalue, on vous paie. Une":"You sell, we assess, we pay you. A","offre ferme et chiffrée":"firm, quantified offer","remise sur place après inspection — sans intermédiaire, sans annonce à gérer, sans attente.":"handed over on the spot after inspection — no middleman, no ad to manage, no waiting.",
"Estimation par WhatsApp":"Valuation via WhatsApp","Offre en ~30 minutes":"Offer in ~30 minutes","Estimation 100% gratuite":"100% free valuation","On se déplace chez vous":"We come to you","Paiement sécurisé & rapide":"Fast & secure payment",
"Pourquoi nous confier votre véhicule":"Why entrust us with your vehicle","La vente de votre voiture, en mode express":"Selling your car, express mode",
"Fini les acheteurs qui se désistent, les rendez-vous sans suite et les négociations interminables. On s'occupe de tout, vous repartez payé.":"No more buyers backing out, dead-end appointments and endless negotiations. We handle everything, you leave paid.",
"Évaluation immédiate":"Immediate valuation",
"Un prix de rachat ferme, annoncé sur place le jour même — pas d'estimation « à la louche » par téléphone.":"A firm buyback price, announced on the spot the same day — no rough phone estimates.",
"On vient à vous":"We come to you",
"À votre domicile, sur votre lieu de travail ou dans l'une de nos agences : c'est vous qui choisissez.":"At your home, your workplace or one of our branches: you choose.",
"Paiement rapide & sûr":"Fast & safe payment",
"Règlement sécurisé sous 24 à 48h et démarches administratives (carte grise, cession) gérées par nos soins.":"Secure payment within 24 to 48 hours and paperwork (registration, transfer) handled by us.",
"De nombreux profils":"Many profiles",
"Récente ou ancienne, citadine, SUV ou utilitaire, essence, diesel ou électrique : on étudie votre véhicule.":"Recent or older, city car, SUV or van, petrol, diesel or electric: we consider your vehicle.",
"Notre promesse":"Our promise","Pas de blabla. Une inspection, un prix, du cash.":"No fuss. One inspection, one price, cash.",
"Vous savez exactement combien vaut votre véhicule avant de repartir. Vous acceptez ou non — sans aucun engagement.":"You know exactly what your vehicle is worth before you leave. You accept or not — with no obligation.",
"Je veux mon estimation gratuite":"I want my free valuation",
"Du premier contact au cash, en 5 étapes":"From first contact to cash, in 5 steps",
"Un parcours simple, transparent et rapide, mené par un expert SJA Passion 73.":"A simple, transparent and fast process, led by an SJA Passion 73 expert.",
"Vous nous contactez":"You contact us",
"Décrivez votre véhicule en 2 minutes : par téléphone, WhatsApp ou via le formulaire.":"Describe your vehicle in 2 minutes: by phone, WhatsApp or the form.",
"On fixe le rendez-vous":"We set the appointment",
"On se déplace chez vous ou vous venez dans l'une de nos agences — au choix, sans frais.":"We come to you or you visit one of our branches — your choice, free of charge.",
"Inspection & vérifications":"Inspection & checks",
"Notre expert contrôle l'état, l'historique, les documents et fait un essai.":"Our expert checks the condition, history, documents and takes a test drive.",
"Offre chiffrée immédiate":"Immediate quantified offer",
"Un prix de rachat ferme, annoncé sur place — sans engagement de votre part.":"A firm buyback price, announced on the spot — with no obligation on your part.",
"Paiement & démarches":"Payment & paperwork",
"Vous acceptez : on gère la cession et vous êtes réglé rapidement, en toute sécurité.":"You accept: we handle the transfer and you are paid quickly and securely.",
"Estimation gratuite et sans engagement.":"Free valuation with no obligation.",
"L'inspection et l'offre de rachat ne vous coûtent rien. Vous restez libre d'accepter ou de refuser notre proposition.":"The inspection and buyback offer cost you nothing. You remain free to accept or decline our proposal.",
"Ce que nous rachetons":"What we buy","Presque toutes les voitures nous intéressent":"Almost every car interests us",
"Toutes marques, toutes énergies, tout kilométrage — pour les véhicules en bon état de marche.":"All brands, all fuels, any mileage — for vehicles in good running order.",
"Toutes les marques":"All brands","Essence · Diesel":"Petrol · Diesel","Hybride · Électrique":"Hybrid · Electric","Récentes ou anciennes":"Recent or older","Fort kilométrage":"High mileage","Roulantes & en bon état":"Running & in good condition","Avec ou sans contrôle technique":"With or without MOT","Utilitaires & SUV":"Vans & SUVs",
"Documents à prévoir":"Documents to prepare",
"Pour aller vite le jour du rendez-vous, préparez si possible :":"To speed things up on the day, prepare if possible:",
"Carte grise (certificat d'immatriculation) à votre nom":"Registration certificate in your name",
"Contrôle technique de moins de 6 mois (véhicules de + de 4 ans)":"MOT less than 6 months old (vehicles over 4 years)",
"Pièce d'identité en cours de validité":"Valid ID document",
"Double des clés + carnet d'entretien si disponible":"Spare keys + service book if available",
"RIB pour le règlement":"Bank details for payment",
"Nous ne rachetons pas les véhicules accidentés ou non roulants.":"We do not buy damaged or non-running vehicles.",
"Estimation gratuite & sans engagement":"Free valuation & no obligation","Recevez votre offre de rachat":"Receive your buyback offer",
"Renseignez votre véhicule en quelques secondes. On vous recontacte rapidement pour caler l'inspection et vous remettre une offre ferme.":"Describe your vehicle in a few seconds. We will get back to you quickly to schedule the inspection and hand you a firm offer.",
"Merci ! Votre demande d'estimation est bien partie — on vous recontacte très vite.":"Thank you! Your valuation request has been sent — we will get back to you very soon.",
"Veuillez indiquer un numéro.":"Please enter a number.","Email invalide.":"Invalid email.","Ville / Code postal":"City / Postcode","Marque & modèle":"Make & model","Indiquez le véhicule.":"Please specify the vehicle.","Kilométrage":"Mileage","État général":"Overall condition","— Sélectionnez —":"— Select —","Excellent":"Excellent","Bon":"Good","Correct / à rafraîchir":"Fair / needs freshening up",
"Précisions (options, historique, disponibilités…)":"Details (options, history, availability…)","Recevoir mon estimation":"Get my estimate",
"SJA Passion 73 se réserve le droit de ne pas proposer de rachat selon l'état et le profil du véhicule.":"SJA Passion 73 reserves the right not to make a buyback offer depending on the vehicle's condition and profile.",
"Votre expert de la vente et de l'importation de véhicules depuis plus de 20 ans — et désormais le rachat cash de votre voiture, partout en France.":"Your vehicle sales and import expert for over 20 years — and now cash buyback of your car, anywhere in France.",
"Nos activités":"Our activities","Vente de véhicules":"Vehicle sales","Export & livraison":"Export & delivery","Demander une offre":"Request an offer",
"Des véhicules":"Vehicles","au-delà des frontières européennes.":"beyond European borders.",
"Une sélection de véhicules hors normes UE, réservés à l'export en dehors de l'Union Européenne — pour les marchés qui n'exigent pas la conformité européenne.":"A selection of non-EU-standard vehicles, reserved for export outside the European Union — for markets that do not require European compliance.",
"Voir les annonces":"See the listings","Nos véhicules — export hors UE":"Our vehicles — export outside EU","Sélection à venir":"Selection coming soon",
"Filtrez par marque, état et budget parmi notre future sélection réservée à l'export hors Union Européenne.":"Filter by brand, condition and budget from our upcoming selection reserved for export outside the European Union.",
"Bientôt":"Soon","Annonce à venir":"Listing coming soon","Véhicule en cours de préparation pour l'export.":"Vehicle being prepared for export.",
"Ce qu'il faut savoir":"What you need to know","Une offre dédiée à l'export":"An offer dedicated to export",
"Ces véhicules ne répondent pas aux normes de conformité de l'Union Européenne et ne sont proposés qu'à destination de pays hors UE.":"These vehicles do not meet European Union compliance standards and are only offered for destinations outside the EU.",
"Hors normes UE":"Non-EU standards",
"Véhicules non homologués pour la circulation en Union Européenne, vendus exclusivement pour l'export.":"Vehicles not approved for circulation in the European Union, sold exclusively for export.",
"Export vers l'international":"International export",
"Livraison organisée en dehors de l'Union Européenne, avec accompagnement sur les démarches douanières.":"Delivery organised outside the European Union, with support for customs procedures.",
"Même exigence de qualité":"Same quality standards",
"Chaque véhicule est vérifié par nos équipes avant sa mise en vente, comme pour le reste de notre catalogue.":"Every vehicle is checked by our teams before going on sale, just like the rest of our catalogue.",
"Votre véhicule exporté en 4 étapes":"Your vehicle exported in 4 steps",
"Un parcours simple et transparent, suivi pas à pas par notre équipe, jusqu'à destination hors Union Européenne.":"A simple, transparent journey, followed step by step by our team, all the way to its destination outside the European Union.",
"Sélectionnez votre véhicule hors normes UE dans notre sélection, ou confiez-nous votre recherche.":"Select your non-EU-standard vehicle from our selection, or entrust us with your search.",
"Vente & préparation":"Sale & preparation","Nous gérons la vente":"We handle the sale","hors taxes (HT)":"tax-free (excl. VAT)",", la vérification du véhicule et la préparation au transport international.":", vehicle inspection and preparation for international transport.",
"Acheminement maritime ou routier,":"Sea or road shipping,","dédouanement à l'export":"export customs clearance","et formalités administratives vers le pays de destination hors UE.":"and administrative formalities to the destination country outside the EU.",
"Livraison à destination":"Delivery at destination",
"Votre véhicule est livré hors Union Européenne, prêt à être immatriculé localement —":"Your vehicle is delivered outside the European Union, ready to be registered locally —",
"Vente hors taxes (HT).":"Tax-free sale (excl. VAT).",
"Ces véhicules étant destinés à l'export hors UE, ils peuvent être vendus hors taxes, avec exonération de TVA, sous conditions d'éligibilité.":"As these vehicles are intended for export outside the EU, they can be sold tax-free, with VAT exemption, subject to eligibility conditions.",
"Intéressé ?":"Interested?","Contactez-nous pour être informé des prochaines arrivées":"Contact us to be informed of upcoming arrivals",
"Votre expert de la vente et de l'importation de véhicules depuis plus de 20 ans — en France, en Europe et à l'export hors UE.":"Your vehicle sales and import expert for over 20 years — in France, in Europe and for export outside the EU.",
"Super Promo":"Super Deals","Nos meilleures offres du moment":"Our best offers right now",
"Nos meilleures offres du moment sur des véhicules vendus en France et en Europe — même sélection rigoureuse, prix exceptionnels.":"Our best current offers on vehicles sold in France and Europe — same rigorous selection, exceptional prices.",
"Voir les super promos":"See the super deals",
"Filtrez par marque, état et budget parmi notre sélection en promotion, vendue en France et en Europe.":"Filter by brand, condition and budget from our discounted selection, sold in France and Europe.",
"Nos meilleures offres du moment — véhicules sélectionnés par SJA Passion 73, vendus en France et en Europe.":"Our best current offers — vehicles selected by SJA Passion 73, sold in France and Europe.",
"Super Promo · Extra UE":"Super Deals · Extra EU","Extra UE":"Extra EU",
"Nos meilleures offres du moment sur des véhicules réservés à l'export hors Union Européenne — prix exceptionnels, sous conditions.":"Our best current offers on vehicles reserved for export outside the European Union — exceptional prices, subject to conditions.",
"Filtrez par marque, état et budget parmi notre sélection en promotion, réservée à l'export hors Union Européenne.":"Filter by brand, condition and budget from our discounted selection, reserved for export outside the European Union.",
"Nos meilleures offres du moment — véhicules sélectionnés par SJA Passion 73, réservés à l'export hors Union Européenne.":"Our best current offers — vehicles selected by SJA Passion 73, reserved for export outside the European Union.",
/* Placeholders */
"Votre nom":"Your name","vous@email.com":"you@email.com","+213 ...":"+213 ...","Ex. Dacia Duster 4x4":"E.g. Dacia Duster 4x4","Décrivez votre projet d'importation...":"Describe your import project...",
"06 12 34 56 78":"06 12 34 56 78","Ex. 73260 Aigueblanche":"E.g. 73260 Aigueblanche","Ex. Renault Clio 5":"E.g. Renault Clio 5","Ex. 2021":"E.g. 2021","Ex. 68000":"E.g. 68000","Tout ce qui peut nous aider à évaluer votre véhicule.":"Anything that can help us assess your vehicle.",
/* Contenus dynamiques (cartes, modale, filtres) */
"En stock":"In stock","Sur demande":"On request","Face":"Front","Profil":"Side","Arrière":"Rear","3/4 avant":"3/4 front","Intérieur":"Interior",
"Photos non contractuelles — disponibles à la demande":"Photos not contractually binding — available on request",
"Sièges chauffants":"Heated seats","Volant chauffant":"Heated steering wheel","Aide au stationnement":"Parking assistance","Caméra de recul":"Reversing camera","Navigation GPS":"GPS navigation","Climatisation auto":"Automatic climate control","Toit ouvrant / panoramique":"Sunroof / panoramic roof","Apple CarPlay / Android Auto":"Apple CarPlay / Android Auto","Roue de secours":"Spare wheel",
"Toutes marques":"All brands","Livraison janvier":"Delivery January","Livraison février":"Delivery February","Livraison mars":"Delivery March","Livraison avril":"Delivery April","Livraison mai":"Delivery May","Livraison juin":"Delivery June","Livraison juillet":"Delivery July","Livraison août":"Delivery August","Livraison septembre":"Delivery September","Livraison octobre":"Delivery October","Livraison novembre":"Delivery November","Livraison décembre":"Delivery December",
"manuelle":"manual","automatique":"automatic","Manuelle":"Manual","Automatique":"Automatic","Essence":"Petrol","Diesel":"Diesel","Hybride":"Hybrid","Électrique":"Electric","GPL":"LPG",
"Couleur":"Colour","État":"Condition","Disponibilité":"Availability","Boîte de vitesses":"Gearbox","Prix":"Price","Version":"Version",
"Prix hors taxes · export uniquement":"Price excl. tax · export only","Export hors UE uniquement":"Export outside EU only","SUPER PROMO":"SUPER DEAL","Super promo":"Super deal",
"Demander ce véhicule":"Ask about this vehicle","Contacter":"Contact us","Voir la fiche":"See details","Fermer":"Close",
"Aucun véhicule ne correspond à vos critères.":"No vehicle matches your criteria.","Précédent":"Previous","Suivant":"Next",
"résultat":"result","résultats":"results","véhicule":"vehicle","véhicules":"vehicles",
/* Témoignages */
"Client vérifié":"Verified customer",
"« Une voiture impeccable livrée à Alger en 5 semaines. Suivi du dossier irréprochable du début à la fin. »":"“An immaculate car delivered to Algiers in 5 weeks. Flawless follow-up from start to finish.”",
"« J'avais peur des démarches de douane, SJA a tout géré. Mon Duster est arrivé comme neuf. Je recommande à 100%. »":"“I was worried about customs procedures, SJA handled everything. My Duster arrived like new. I recommend them 100%.”",
"« Prix transparent, aucune mauvaise surprise. Une équipe de vrais professionnels qui connaissent l'export. »":"“Transparent pricing, no bad surprises. A team of true professionals who know the export business.”",
"« Troisième véhicule importé avec eux pour ma société. Sérieux, rapides, et toujours de bons conseils. »":"“Third vehicle imported with them for my company. Reliable, fast, and always good advice.”",
"Livraison Alger":"Delivery to Algiers","Témoignage client":"Customer testimonial","Dédouanement expliqué":"Customs clearance explained","Showroom":"Showroom","Visite showroom":"Showroom tour","Dédouanement":"Customs clearance"
};
